"""Docs catalog generator.

Imports every servers/*/server.py in isolation (unique module names), uses the
FastMCP in-memory Client to list each server's tools (name + first docstring line
+ params), and writes:
  - TOOLS.md   : catalog grouped by server, with a top summary table.
  - README.md  : a short '## Tool catalog' pointer section (appended if missing).

Offline only: importing + in-memory listing never touches the network.
Run: VIRTUAL_ENV= .venv/bin/python tests/gen_docs.py
"""
from __future__ import annotations

import asyncio
import importlib.util
import sys
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SERVERS_DIR = ROOT / "servers"
TOOLS_MD = ROOT / "TOOLS.md"
README_MD = ROOT / "README.md"

from fastmcp import Client  # noqa: E402


def import_server(name: str):
    """Import servers/<name>/server.py under a unique module name."""
    path = SERVERS_DIR / name / "server.py"
    modname = f"docsrv_{name.replace('-', '_')}"
    # Make the server's own dir importable (some servers import sibling modules),
    # but remove it again afterward so servers don't shadow each other.
    srv_dir = str(path.parent)
    sys.path.insert(0, srv_dir)
    try:
        spec = importlib.util.spec_from_file_location(modname, path)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[modname] = mod
        spec.loader.exec_module(mod)
        return mod
    finally:
        try:
            sys.path.remove(srv_dir)
        except ValueError:
            pass


def first_line(text: str | None) -> str:
    if not text:
        return ""
    for ln in text.strip().splitlines():
        ln = ln.strip()
        if ln:
            return ln
    return ""


def server_purpose(mod) -> str:
    """One-line purpose from the FastMCP instructions or the module docstring."""
    instr = getattr(getattr(mod, "mcp", None), "instructions", None)
    line = first_line(instr) or first_line(getattr(mod, "__doc__", None))
    return line


def param_names(tool) -> list[str]:
    schema = getattr(tool, "inputSchema", None) or {}
    props = schema.get("properties", {}) if isinstance(schema, dict) else {}
    required = set(schema.get("required", []) if isinstance(schema, dict) else [])
    out = []
    for pname in props:
        out.append(pname if pname in required else f"{pname}?")
    return out


async def list_tools(mod):
    async with Client(mod.mcp) as c:
        tools = await c.list_tools()
    rows = []
    for t in sorted(tools, key=lambda x: x.name):
        rows.append(
            {
                "name": t.name,
                "desc": first_line(getattr(t, "description", "")),
                "params": param_names(t),
            }
        )
    return rows


def md_escape(s: str) -> str:
    return s.replace("|", "\\|")


def main() -> int:
    names = sorted(p.parent.name for p in SERVERS_DIR.glob("*/server.py"))
    catalog: list[dict] = []
    failures: list[tuple[str, str]] = []

    for name in names:
        try:
            mod = import_server(name)
            purpose = server_purpose(mod)
            tools = asyncio.run(list_tools(mod))
            catalog.append({"name": name, "purpose": purpose, "tools": tools})
        except Exception:
            failures.append((name, traceback.format_exc().strip().splitlines()[-1]))

    total_tools = sum(len(c["tools"]) for c in catalog)

    # ---- Build TOOLS.md ----
    out: list[str] = []
    out.append("# Tool catalog")
    out.append("")
    out.append(
        f"Auto-generated by `tests/gen_docs.py`. "
        f"**{len(catalog)} servers**, **{total_tools} tools** total."
    )
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append("| Server | #Tools | Purpose |")
    out.append("| --- | ---: | --- |")
    for c in catalog:
        out.append(
            f"| [`{c['name']}`](#{c['name']}) | {len(c['tools'])} | "
            f"{md_escape(c['purpose'])} |"
        )
    out.append("")

    out.append("## Servers")
    out.append("")
    for c in catalog:
        out.append(f"### {c['name']}")
        out.append("")
        if c["purpose"]:
            out.append(f"_{c['purpose']}_")
            out.append("")
        if not c["tools"]:
            out.append("_(no tools registered)_")
            out.append("")
            continue
        for t in c["tools"]:
            params = ", ".join(t["params"])
            sig = f"`{t['name']}({params})`"
            desc = f" — {t['desc']}" if t["desc"] else ""
            out.append(f"- {sig}{desc}")
        out.append("")

    if failures:
        out.append("## Failed to import")
        out.append("")
        for name, err in failures:
            out.append(f"- `{name}`: {md_escape(err)}")
        out.append("")

    TOOLS_MD.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")

    # ---- README.md pointer section (append if missing) ----
    marker = "## Tool catalog"
    readme = README_MD.read_text(encoding="utf-8") if README_MD.exists() else ""
    if marker not in readme:
        section = (
            f"\n{marker}\n\n"
            f"See [`TOOLS.md`](TOOLS.md) for the full catalog of every server and its "
            f"tools ({len(catalog)} servers, {total_tools} tools), auto-generated by "
            f"`tests/gen_docs.py`.\n"
        )
        with README_MD.open("a", encoding="utf-8") as f:
            f.write(section)
        readme_action = "appended pointer section"
    else:
        readme_action = "pointer section already present (left unchanged)"

    print(f"Wrote {TOOLS_MD} ({len(catalog)} servers, {total_tools} tools)")
    print(f"README.md: {readme_action}")
    if failures:
        print(f"WARNING: {len(failures)} server(s) failed to import:")
        for name, err in failures:
            print(f"  - {name}: {err}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
